services:
  - type: web
    name: signaling-server
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
